=== jbrown1618/pokemon/src/main/resources/config/SpeciesConfigSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="pokemon.jbrown.com"
           elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="SpeciesConfig">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Species" type="Species" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element name="GenerationDate" type="xs:date"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="Species">
        <xs:sequence>
            <xs:element name="Id" type="xs:int"/>
            <xs:element name="Name" type="xs:string"/>
            <xs:element name="Type1" type="xs:string"/>
            <xs:element name="Type2" type="xs:string"/>
            <xs:element name="PokedexEntry" type="xs:string"/>
            <xs:element name="BaseStats" type="Stats"/>
            <xs:element name="LearnSet" type="LearnSet"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Stats">
        <xs:sequence>
            <xs:element name="HP" type="xs:int"/>
            <xs:element name="Attack" type="xs:int"/>
            <xs:element name="Defense" type="xs:int"/>
            <xs:element name="SpecialAttack" type="xs:int"/>
            <xs:element name="SpecialDefense" type="xs:int"/>
            <xs:element name="Speed" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="LearnSet">
        <xs:sequence>
            <xs:element name="LevelUpMoves" type="MoveList"/>
            <xs:element name="TmHmMoves" type="MoveList"/>
            <xs:element name="EggMoves" type="MoveList"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="MoveList">
        <xs:sequence>
            <xs:element name="MoveName" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== jbrown1618/pokemon/src/main/resources/config/SpeciesConfig.xml
<?xml version="1.0" encoding="utf-8"?>
<SpeciesConfig xmlns="pokemon.jbrown.com"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="pokemon.jbrown.com SpeciesConfigSchema.xsd">
    <Species>
        <Id>1</Id>
        <Name>Bulbasaur</Name>
        <Type1>Grass</Type1>
        <Type2/>
        <PokedexEntry>Lorem ipsum dolor sit amet...</PokedexEntry>
        <BaseStats>
            <HP>45</HP>
            <Attack>49</Attack>
            <Defense>49</Defense>
            <SpecialAttack>65</SpecialAttack>
            <SpecialDefense>65</SpecialDefense>
            <Speed>45</Speed>
        </BaseStats>
        <LearnSet>
            <LevelUpMoves>
                <MoveName>Tackle</MoveName>
            </LevelUpMoves>
            <TmHmMoves>
                <MoveName>SolarBeam</MoveName>
            </TmHmMoves>
            <EggMoves>
                <MoveName>Petal Dance</MoveName>
            </EggMoves>
        </LearnSet>
    </Species>
    <Species>
        <Id>2</Id>
        <Name>Ivysaur</Name>
        <Type1>Grass</Type1>
        <Type2>Poison</Type2>
        <PokedexEntry>Lorem ipsum dolor sit amet...</PokedexEntry>
        <BaseStats>
            <HP>45</HP>
            <Attack>49</Attack>
            <Defense>49</Defense>
            <SpecialAttack>65</SpecialAttack>
            <SpecialDefense>65</SpecialDefense>
            <Speed>45</Speed>
        </BaseStats>
        <LearnSet>
            <LevelUpMoves>
                <MoveName>Tackle</MoveName>
            </LevelUpMoves>
            <TmHmMoves>
                <MoveName>SolarBeam</MoveName>
            </TmHmMoves>
            <EggMoves>
                <MoveName>Petal Dance</MoveName>
            </EggMoves>
        </LearnSet>
    </Species>
    <GenerationDate>2016-12-28</GenerationDate>
</SpeciesConfig>
